name: hisotech
description: Flutter Cross-Platform Webview Application made for Flipeverest Company.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.13.1
  onesignal_flutter: ^5.4.1
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.1.0
  phosphor_flutter: ^2.1.0
  shimmer: ^3.0.0

  # ===== LOCAL DATABASE =====
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0

  # ===== WEB SCRAPING =====
  http: ^1.2.2
  html: ^0.15.4

  # ===== GEO LOCATION =====
  geolocator: ^11.0.0

  # ===== IMAGE CACHE =====
  cached_network_image: ^3.3.1

  # ===== LOCAL STORAGE =====
  shared_preferences: ^2.2.2

  # ===== OPEN LINK =====
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

# ==============================
# FLUTTER NATIVE SPLASH
# ==============================

flutter_native_splash:

  # nền splash
  color: "#16A34A"

  android: true
  ios: true
  web: false

  android_12:
    color: "#16A34A"